
["Arrow turret"]
	#In ticks
	#Range: 10 ~ 60
	"Fire rate" = 20
	#Range: 10.0 ~ 500.0
	Health = 60.0
	#Range: 0.0 ~ 100.0
	Armor = 3.0
	#Range: 1 ~ 100
	"Base damage" = 12
	#Range: 8.0 ~ 100.0
	Range = 32.0

["Bullet turret"]
	#In ticks
	#Range: 10 ~ 60
	"Fire rate" = 20
	#Range: 10.0 ~ 500.0
	Health = 60.0
	#Range: 0.0 ~ 100.0
	Armor = 3.0
	#Range: 1 ~ 100
	"Iron bullet damage" = 16
	#Range: 8.0 ~ 100.0
	Range = 32.0
	#Range: 1 ~ 100
	"Gold bullet damage" = 14

["Fire charge turret"]
	#In ticks
	#Range: 10 ~ 60
	"Fire rate" = 20
	#Range: 10.0 ~ 500.0
	Health = 60.0
	#Range: 0.0 ~ 100.0
	Armor = 3.0
	#Range: 8.0 ~ 100.0
	Range = 32.0
	#Range: 1 ~ 100
	Damage = 12

["Brick turret"]
	#Range: 1 ~ 100
	"Brick damage" = 18
	#In ticks
	#Range: 10 ~ 60
	"Fire rate" = 20
	#Range: 10.0 ~ 500.0
	Health = 60.0
	#Range: 0.0 ~ 100.0
	Armor = 3.0
	#Range: 8.0 ~ 100.0
	Range = 32.0
	#Range: 1 ~ 100
	"Nether brick damage" = 20

["Gauss turret"]
	#In ticks
	#Range: 10 ~ 60
	"Fire rate" = 20
	#Range: 10.0 ~ 500.0
	Health = 60.0
	#Range: 0.0 ~ 100.0
	Armor = 3.0
	#Range: 8.0 ~ 100.0
	Range = 32.0
	#Range: 1 ~ 100
	Damage = 48

["Cobble turret"]
	#In ticks
	#Range: 10 ~ 60
	"Fire rate" = 20
	#Range: 10.0 ~ 500.0
	Health = 60.0
	#Range: 0.0 ~ 100.0
	Armor = 3.0
	#Range: 0.0 ~ 100.0
	Range = 32.0
	#Range: 1 ~ 100
	Damage = 6

